name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        run: |
          scp -r -o StrictHostKeyChecking=no . ubuntu@15.207.19.12:/home/ubuntu/bunOdooAPI
      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.207.19.12 << 'EOF'
            cd /home/ubuntu/bunOdooAPI
            pm2 restart server.js --name my-odoo-api || pm2 start server.js --name my-odoo-api
          EOF
